{
  "hash": "a17652140a2542cdfa57c25e90858176",
  "result": {
    "markdown": "---\ntitle: \"Structural Equation Modelling\"\ndescription: \"This post is a walkthrough of a structural equation model in R.\"\nauthor: \"Matthias Quinn\"\ndate: \"8/12/2022\"\naffiliation: Progressive Insurance\nprogress: true\ncode-copy: true\ncategories:\n  - code\n  - statistics\nimage: \"lavaan.png\"\nimage-alt: \"Lavaan in R\"\nformat: html\ncache: true\n---\n\n\n::: columns\n::: {.column width=\"40%\"}\n## GOAL\n\nLearn how to create and interpret structural equation models using R's lavaan.\n:::\n\n::: {.column width=\"10%\"}\n<!-- empty column to create gap -->\n:::\n\n::: {.column width=\"40%\"}\n## RESULT\n\n**WiP**\n:::\n:::\n\nStructural Equation Models (SEM) help to model the dependence relationships among multiple variables, simultaneously. In other words, we can model not only multiple variables, but each of those dependent variables can have multiple covariates attached to them.\n\n### Software\n\nThere are a plethora of options available to create SEMs. Here are just a few of them:\n\n1.  [lavaan](https://lavaan.ugent.be/)\n2.  [MPlus](https://www.statmodel.com/)\n3.  [SAS](https://documentation.sas.com/doc/en/statug/15.2/statug_calis_overview09.htm)\n4.  [Stata](https://www.stata.com/features/structural-equation-modeling/)\n\nThis project will use the **lavaan** library. If you don't have it installed, simply run the following command in your IDE of choice:\n\n\n::: {.cell hash='SEM-Indices_cache/html/unnamed-chunk-1_5063d820d506c1747fd5f73b0b41a2bf'}\n\n```{.r .cell-code}\n# install.packages(\"lavaan\", dependencies=TRUE)\nlibrary(lavaan)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'lavaan' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is lavaan 0.6-12\nlavaan is FREE software! Please report any bugs.\n```\n:::\n:::\n\n\nBTW, this walk-through is my interpretation of the fantastic [guide](https://stats.oarc.ucla.edu/r/seminars/rsem/) created by UCLA.\n\n### Introduction\n\nStructural equation modeling is a linear model framework that models concrete regression equations with latent variables.\n\n### Motivating Example\n\nSuppose you are a researcher studying the effects of student background on academic achievement. The lab recently finished collecting and uploading the dataset ([worland5.csv](https://stats.idre.ucla.edu/wp-content/uploads/2021/02/worland5.csv)) of $N= 500$ students with $9$ observed variables for each student. The principal investigator hypothesizes three latent constructs Adjustment, Risk, Achievement measured with its corresponding to the following codebook mapping:\n\n**Adjustment:**\n\n-   motiv Motivation\n\n-   harm Harmony\n\n-   stabi Stability\n\n**Risk:**\n\n-   ppsych (Negative) Parental Psychology\n\n-   ses Socio-economic Status\n\n-   verbal Verbal IQ\n\n**Achievement:**\n\n-   read Reading\n\n-   arith Arithmetic\n\n-   spell Spelling\n\nHere's how to download and load the dataset into R:\n\n\n::: {.cell hash='SEM-Indices_cache/html/unnamed-chunk-2_69e64d90dad39bfe41c5bc49ae921a5a'}\n\n```{.r .cell-code}\ndat <- read.csv(\"https://stats.idre.ucla.edu/wp-content/uploads/2021/02/worland5.csv\")\n```\n:::\n\n\n::: {.callout-important collapse=\"true\"}\n## Key\n\nThe most essential component of a structural equation model is **covariance** or the statistical relationship between items. The true population covariance, denoted $\\Sigma$, is called the variance-covariance matrix. Since you don't ever know the true $\\Sigma$, you can estimate it with your sample data. We call this the sample variance-covariance matrix, or $\\hat{\\Sigma}$.\n:::\n\nThe variance-covariance matrix $\\Sigma$ should not be confused with $\\Sigma(\\theta)$ which is the model. However, if the model fits perfectly, then $\\Sigma = \\Sigma(\\theta)$.\n\n::: {.callout-note collapse=\"true\"}\nRunning the **cov** command in R allows us to obtain the population variance-covariance matrix $\\Sigma$?\n\n*Answer*: False, the `cov` command obtains the sample, or $S$.\n:::\n\n### Definitions\n\n-   **observed variable:** a variable that exists in the data, a.k.a **item** or manifest variable\n\n<!-- -->\n\n-   **latent variable:** a variable that is constructed and does not exist in the data\n\n-   **exogenous variable:** an independent variable either observed (x) or latent ($\\Xi$) that explains an endogenous variable\n\n-   **endogenous variable:** a dependent variable, either observed (y) or latent ($\\eta$) that has a causal path leading to it\n\n-   **measurement model:** a model that links observed variables with latent variables\n\n-   **indicator:** an observed variable in a measurement model (can be exogenous or endogenous)\n\n-   **factor**: a latent variable defined by its indicators (can be exogenous or endogenous)\n\n-   **loading:** a path between an indicator and a factor\n\n-   **structural model:** a model that specifies causal relationships among exogenous variables to endogenous variables (can be observed or latent)\n\n-   **regression path:** a path between exogenous and endogenous variables (can be observed or latent)\n\n-   $x_1$, a single exogenous variable\n\n-   $y_1$, single endogenous variable\n\n-   $\\beta_0, \\alpha_1$, intercept of $y_1$, \"alpha\"\n\n-   $\\beta_1, \\gamma_1$, regression coefficient, \"gamma\"\n\n-   $\\phi$, variance or covariance of the exogenous variable, \"phi\"\n\n-   $\\psi$, residual variance or covariance of the endogenous variable, \"psi\"\n\n### The path model\n\n![Copyright UCLA](Path%20Diagram%20Legend.png)\n\n### lavaan syntax\n\nBefore running our first regression analysis, let us introduce some of the most frequently used syntax in **`lavaan`**\n\n-   **`~`** **predict**, used for regression of observed outcome to observed predictors (e.g., **`y ~ x`**)\n\n-   **`=~`** **indicator**, used for latent variable to observed indicator in factor analysis measurement models (e.g., **`f =~ q + r + s`**)\n\n-   **`~~`** **covariance** (e.g., **`x ~~ x`**)\n\n-   **`~1`** **intercept** or mean (e.g., **`x ~ 1`** estimates the mean of variable **`x`**)\n\n-   **`1*`** **fixes** **parameter** or loading to one (e.g., **`f =~ 1*q`**)\n\n-   **`NA*`** **frees** **parameter** or loading (useful to override default marker method, (e.g., **`f =~ NA*q`**)\n\n-   **`a*`** **labels** the **parameter** 'a', used for model constraints (e.g., **`f =~ a*q`**)\n\n### Simple regression\n\nSimple regression models the relationship of an observed exogenous variable on a single observed endogenous variable. For a single subject, the simple linear regression equation is most commonly defined as:\n\n$$\ny_1 = \\beta_0 + \\beta_1x_1 + \\epsilon_1\n$$\n\n![Copyright UCLA](UCLA%20-%20Model%201A.png){fig-align=\"center\"}\n\nIn R, the most basic way to run a linear regression is to use the `lm()` function:\n\n\n::: {.cell hash='SEM-Indices_cache/html/unnamed-chunk-3_edc695bbcf2cec2ecacce8071187c0e4'}\n\n```{.r .cell-code}\n#simple regression using lm()\nm1a <- lm(read ~ motiv, data=dat)\n(fit1a <-summary(m1a))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = read ~ motiv, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.0995  -6.1109   0.2342   5.2237  24.0183 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.232e-07  3.796e-01    0.00        1    \nmotiv        5.300e-01  3.800e-02   13.95   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.488 on 498 degrees of freedom\nMultiple R-squared:  0.2809,\tAdjusted R-squared:  0.2795 \nF-statistic: 194.5 on 1 and 498 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe predicted mean of **`read`** is $0$ for a student with **`motiv`**=$0$ and for a one unit increase in motivation, the reading score improves $0.530$ points. Make special note of the residual standard error which is 8.488. The square of that $8.4882=72.04$ is the residual variance, which we will see later in **`lavaan()`**. We can run the equivalent code in lavaan. The syntax is very similar to **`lm()`** in that **`read ~ motiv`** specifies the predictor **`motiv`** on the outcome **`read`**. However, by default the intercept is not included in the output but is implied. If we want to add an intercept, we need to include **`read ~ 1 + motiv`**. Optionally, you can request the variance of **`motiv`** using **`motiv ~~ motiv`**. If this syntax is not provided, the parameter is still estimated but just implied.\n\n\n::: {.cell hash='SEM-Indices_cache/html/unnamed-chunk-4_016097f1c23e6d875d2cec534cbdc174'}\n\n```{.r .cell-code}\nlibrary(lavaan)\n\n#simple regression using lavaan \nmodelOne <- \"\n  # regressions\n    read ~ 1 + motiv\n  # variance (optional)\n    motiv ~~ motiv\n\"\nfitOne <- sem(modelOne, data=dat)\n\nsummary(fitOne)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlavaan 0.6-12 ended normally after 8 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         5\n\n  Number of observations                           500\n\nModel Test User Model:\n                                                      \n  Test statistic                                 0.000\n  Degrees of freedom                                 0\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  read ~                                              \n    motiv             0.530    0.038   13.975    0.000\n\nIntercepts:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .read             -0.000    0.379   -0.000    1.000\n    motiv             0.000    0.447    0.000    1.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n    motiv            99.800    6.312   15.811    0.000\n   .read             71.766    4.539   15.811    0.000\n```\n:::\n:::\n\n\nNotice how the intercept of `read (0.000)` and the regression coefficient of `read ~ motiv (0.530)` matches the output of the linear model, with small rounding errors. The intercept for `motiv (0.000)` does not have a `.` and neither does its variance of $99.80$, meaning that it's an exogenous mean and variance.\n\nAlso, an important piece of output is that the estimator of use is **M.L.**, also known as **Maximum Likelihood**. The `lm()` function uses the least squares estimator.\n\n::: {.callout-important collapse=\"true\"}\n## Small Note\n\nThe `.` in front of the parameter denotes an endogenous variable under intercepts and a residual variance if it's under Variances or Co-variances.\n:::\n\n### Maximum Likelihood vs. Least Squares Estimators\n\nFor **least squares**, the estimate for the residual variance is:\n\n$$\n\\hat{\\sigma}^2_{LS} = \\frac{\\sum_{i=1}^{N} \\hat{\\zeta_i}^2}{N-k}\n$$\n\nwhere $N$ is the sample size and $k$ is the number of predictors $+1$ for the intercept. For **maximum likelihood**, the estimate for the residual variance is:\n\n$$\n\\hat{\\sigma}^2_{ML} = \\frac{\\sum_{i=1}^{N} \\hat{\\zeta_i}^2}{N}\n$$\n\nHere is the conversion between the two methods for the residual variance:\n\n$$\n\\hat{\\sigma}^2_{ML} = \\left(\\frac{N-k}{n}\\right) \\hat{\\sigma}^2_{LS}\n$$\n\nYou can tell *lavaan* to use a generalized least squares estimator by calling `estimator=GLS` in the fit function.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}