project: 
  type: website
  
execute: 
  freeze: true
  
website:
  page-navigation: true
  title: "N3uralN3twork's Website"
  site-url: "https://openscapes.github.io/quarto-website-tutorial" 
  repo-url: https://github.com/N3uralN3twork/n3uraln3twork.github.io
  repo-actions: [edit, issue]
  favicon: "images/Combo-Chart-Icon.png"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Matthias Quinn, 2022"
    
  sidebar:
    logo: "images/Orange_Banner_Background.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://github.com/N3uralN3twork/n3uraln3twork.github.io
        text: "Website"
      - icon: github
        href: https://github.com/N3uralN3twork
        text: "Personal Github"
      - icon: linkedin
        href: https://www.linkedin.com/in/matthiasquinn
        text: "Personal Linkedin"
      - icon: "question-circle"
        href: mailto:miq_qedquinn@yahoo.com
        text: "Contact Me"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: aboutme.qmd
        text: Who am I?
      - href: resumes.qmd
        text: Resumes
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Papers


format:
  html:
    theme:
      light: [journal] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cyborg]
    code-copy: true
    code-overflow: wrap
    toc: true
    linkcolor: orange
    code-fold: true
    code-line-numbers: true
    html-math-method: katex


filters:
  - include-files.lua
  - quarto

  



